name: Deploy site

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'assets/**'
      - '**.bib'
      - '**.html'
      - '**.js'
      - '**.liquid'
      - '**/*.md'
      - '**.yml'
      - 'Gemfile'
      - 'Gemfile.lock'
      - '!.github/workflows/**'
      - '!lighthouse_results/**'
      - '!CONTRIBUTING.md'
      - '!CUSTOMIZE.md'
      - '!FAQ.md'
      - '!INSTALL.md'
      - '!README.md'
  pull_request:
    branches:
      - master
      - main
    paths:
      - 'assets/**'
      - '**.bib'
      - '**.html'
      - '**.js'
      - '**.liquid'
      - '**/*.md'
      - '**.yml'
      - 'Gemfile'
      - 'Gemfile.lock'
      - '!.github/workflows/**'
      - '!lighthouse_results/**'
      - '!CONTRIBUTING.md'
      - '!CUSTOMIZE.md'
      - '!FAQ.md'
      - '!INSTALL.md'
      - '!README.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensure submodules are checked out if any

      - name: Setup Ruby ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'  # Update to match the theme's required Ruby version
          bundler-cache: true    # Caches gems automatically

      - name: Setup Python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Use a stable Python version
          cache: 'pip'           # Cache pip dependencies

      - name: Update _config.yml âš™ï¸
        uses: fjogeleit/yaml-update-action@v1.1
        with:
          file: '_config.yml'
          property-path: 'giscus.repo'
          value: ${{ github.repository }}
          commit-change: false

      - name: Install Dependencies ğŸ”§
        run: |
          pip3 install --upgrade nbconvert
          bundle install

      - name: Build Site ğŸ—ï¸
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build

      - name: Purge Unused CSS ğŸ§¹
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js

      - name: Deploy ğŸš€
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
